package com.aitiniubi.medicalbooktranslator;

import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;
import com.aitiniubi.medicalbooktranslator.epub.*;import com.aitiniubi.medicalbooktranslator.translation.*;
import java.io.*;import java.util.*;

public class MainActivity extends Activity {
    private TextView status,report; private ProgressBar progress; private Button analyze,translate,export; private File selectedFile,lastOutput; private EpubBook book;
    private android.content.SharedPreferences prefsHolder;
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(com.aitiniubi.medicalbooktranslator.R.layout.activity_main);prefsHolder=getSharedPreferences("config",MODE_PRIVATE);
        status=findViewById(R.id.status);report=findViewById(R.id.report);progress=findViewById(R.id.progress);Button open=findViewById(R.id.openButton);analyze=findViewById(R.id.analyzeButton);translate=findViewById(R.id.translateButton);Button settings=findViewById(R.id.settingsButton);export=findViewById(R.id.exportButton);
        open.setOnClickListener(v->pick());analyze.setOnClickListener(v->analyze());settings.setOnClickListener(v->settings());translate.setOnClickListener(v->translate());export.setOnClickListener(v->saveOutput());
    }
    private void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/epub+zip");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,10);}
    @Override protected void onActivityResult(int r,int c, Intent d){super.onActivityResult(r,c,d);if(r==11&&c==RESULT_OK&&d!=null){try{try(InputStream in=new FileInputStream(lastOutput);OutputStream out=getContentResolver().openOutputStream(d.getData())){byte[]b=new byte[16384];int n;while((n=in.read(b))>0)out.write(b,0,n);}Toast.makeText(this,"Đã xuất EPUB",Toast.LENGTH_LONG).show();}catch(Exception e){showError(e);}return;}if(r==10&&c==RESULT_OK&&d!=null){try{Uri u=d.getData();selectedFile=new File(getCacheDir(),"input.epub");try(InputStream in=getContentResolver().openInputStream(u);FileOutputStream out=new FileOutputStream(selectedFile)){byte[]b=new byte[16384];int n;while((n=in.read(b))>0)out.write(b,0,n);}status.setText("Đã chọn: "+u.getLastPathSegment());analyze.setEnabled(true);translate.setEnabled(true);}catch(Exception e){showError(e);}}}
    private void analyze(){if(selectedFile==null)return;progress.setVisibility(View.VISIBLE);progress.setIndeterminate(true);report.setText("Đang phân tích cấu trúc EPUB…");new Thread(()->{try{book=EpubAnalyzer.analyze(selectedFile);runOnUiThread(()->{progress.setVisibility(View.GONE);progress.setIndeterminate(false);report.setText("EPUB: "+book.title+"\nFiles: "+book.totalFiles+"\nXHTML: "+book.xhtmlFiles.size()+"\nĐoạn văn: "+book.paragraphCount+"\nHình/ảnh tham chiếu: "+book.imageReferenceCount+"\nFigure: "+book.figureCount+"\nBảng: "+book.tableCount+"\n\nCấu trúc gốc sẽ được giữ nguyên khi rebuild.");});}catch(Exception e){runOnUiThread(()->showError(e));}}).start();}
    private TranslationConfig config(){TranslationConfig c=new TranslationConfig();c.endpoint=prefsHolder.getString("endpoint","");c.apiKey=prefsHolder.getString("apiKey","");c.model=prefsHolder.getString("model","");return c;}
    private void settings(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(40,10,40,10);EditText ep=new EditText(this);ep.setHint("OpenAI-compatible endpoint");ep.setText(prefsHolder.getString("endpoint",""));EditText model=new EditText(this);model.setHint("Model");model.setText(prefsHolder.getString("model",""));EditText key=new EditText(this);key.setHint("API key");key.setInputType(129);key.setText(prefsHolder.getString("apiKey",""));box.addView(ep);box.addView(model);box.addView(key);new AlertDialog.Builder(this).setTitle("Cấu hình AI").setView(box).setPositiveButton("Lưu",(d,w)->prefsHolder.edit().putString("endpoint",ep.getText().toString().trim()).putString("model",model.getText().toString().trim()).putString("apiKey",key.getText().toString()).apply()).setNegativeButton("Hủy",null).show();}
    private void translate(){TranslationConfig c=config();if(c.endpoint.isEmpty()||c.model.isEmpty()){settings();return;}File out=new File(getExternalFilesDir(null),"translated_"+System.currentTimeMillis()+".epub");progress.setVisibility(View.VISIBLE);progress.setIndeterminate(false);progress.setMax(100);report.setText("Đang dịch…\nBản gốc vẫn được giữ nguyên.");translate.setEnabled(false);TranslationJob.run(selectedFile,out,c,new TranslationJob.Listener(){public void onProgress(int d,int t){int p=(int)(100.0*d/t);runOnUiThread(()->progress.setProgress(p));}public void onDone(File f){lastOutput=f;runOnUiThread(()->{progress.setProgress(100);translate.setEnabled(true);export.setEnabled(true);report.append("\n\n✓ Đã tạo EPUB: "+f.getAbsolutePath());});}public void onError(Exception e){runOnUiThread(()->{translate.setEnabled(true);showError(e);});}});}
    private void saveOutput(){if(lastOutput==null)return;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/epub+zip");i.putExtra(Intent.EXTRA_TITLE,lastOutput.getName());startActivityForResult(i,11);}
    private void showError(Exception e){progress.setVisibility(View.GONE);new AlertDialog.Builder(this).setTitle("Lỗi").setMessage(e.getMessage()==null?e.toString():e.getMessage()).setPositiveButton("OK",null).show();}
}
